// TypeScript codegen: one .ts per schema into generated/ts/, plus an index.
// Output is committed; CI's drift check re-runs this and fails on a dirty tree.
// (Java codegen is deliberately absent until P2 — event-service is schema-agnostic.)
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compileFromFile } from 'json-schema-to-typescript'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'generated', 'ts')

rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })

const banner = `/* eslint-disable */
/**
 * GENERATED by packages/events/codegen/gen-ts.mjs — DO NOT EDIT.
 * Source of truth: packages/events/schemas. Regenerate with \`task gen\`.
 */`

const exports_ = []
for (const entry of readdirSync(join(root, 'schemas'), { recursive: true, withFileTypes: true })) {
  if (!entry.isFile() || !entry.name.endsWith('.schema.json')) continue
  const moduleName = basename(entry.name, '.schema.json').replace('.', '_') // VillagerSpawned.v1 -> VillagerSpawned_v1
  // No additionalProperties override: schemas declare their own strictness.
  // Open objects (ActionRequested.params, ActionCompleted.result) generate
  // index signatures — their runtime shapes are validated per-action (CIV-7).
  const ts = await compileFromFile(join(entry.parentPath, entry.name), {
    bannerComment: banner,
    cwd: entry.parentPath,
  })
  writeFileSync(join(outDir, `${moduleName}.ts`), ts)
  // Barrel exports ONLY the schema's titled main type — shared $defs names
  // (Position, ...) would collide under `export *` across modules.
  const title = JSON.parse(readFileSync(join(entry.parentPath, entry.name), 'utf8')).title
  exports_.push(`export type { ${title} } from './${moduleName}'`)
  console.log(`ts: ${moduleName}.ts (${title})`)
}

writeFileSync(join(outDir, 'index.ts'), banner + '\n' + exports_.sort().join('\n') + '\n')
console.log(`ts: index.ts (${exports_.length} modules)`)
